#server:
#   port: 8088
   
   
spring:
   application:
      name: xitech-springboot-dubbo-provider

     
dubbo:
   scan:
      base-packages: com.xitech.app.provider.impl
   #dubbo 协议信息
   protocol: 
      name: http
      port: 9999
   registry:
      address: N/A