#server:
#   port: 8088
   
   
spring:
   application:
      name: xitech-springboot-dubbo-provider

     
dubbo:
   scan:
      base-packages: com.xitech.app.provider.impl
   #dubbo 协议信息
   protocol: 
      name: dubbo
      port: 9999
   registry:
      client: curator
      address: zookeeper://127.0.0.1:2181
# zookeeper://10.10.242.45:2181
#N/A #暴露给本地
      