server:
   port: 7777

spring:
   application:
      name: xitech-springcloud-gateway
   cloud:
    gateway:
      enabled: true
      routes:
      - id: test_route
        uri: https://www.jd.com
        predicates:
        - Path=/test   #Path的“首字母一定要大写”
        
logging:
   level:
      org.springframework.cloud.gateway: TRACE
      


management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false