server:
   port: 8081

eureka:
   client:
      service-url:
         defaultZone: http://localhost:9998/eureka/

spring:
   application:
      name: xitech-springcloud-gateway
   cloud:
    gateway:
       discovery:
          locator:
             enabled: true
             lowerCaseServiceId: true
       enabled: true
       routes:
       - id: test_route
         uri: http://localhost:8088/test/head
         filters:
         - AddRequestHeader=testHeader, testHeaderValue 
         predicates:
         - Path=/test   #Path的“首字母一定要大写”
       
      
        
logging:
   level:
      org.springframework.cloud.gateway: DEBUG
      
#http://127.0.0.1:8088/hystrixFeignApi/content/header

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false